name: ステップ 1

on:
  pull_request_target:
    branches: [main]
    types: [opened]

permissions:
  contents: read
  actions: write
  issues: write

env:
  STEP_2_FILE: ".github/steps/2-step.md"

jobs:
  find_exercise:
    name: 演習 Issue を検索
    uses: ./.github/workflows/ja-find-exercise-issue.yml
    with:
      issue-title-text: "演習: マージコンフリクトを解決する"

  post_next_step_content:
    name: 次のステップを投稿
    needs: [find_exercise]
    runs-on: ubuntu-latest
    env:
      ISSUE_REPOSITORY: ${{ github.repository }}
      ISSUE_NUMBER: ${{ needs.find_exercise.outputs.issue-number }}

    steps:
      - name: チェックアウト
        uses: actions/checkout@v4

      - name: コメントを作成 - ステップ完了
        uses: GrantBirki/comment@v2.1.1
        with:
          repository: ${{ env.ISSUE_REPOSITORY }}
          issue-number: ${{ env.ISSUE_NUMBER }}
          file: .github/ja-templates/step-feedback/step-finished-prepare-next-step.md
          vars: |
            next_step_number: 2

      - name: コメントを作成 - ステップ本文
        uses: GrantBirki/comment@v2.1.1
        with:
          repository: ${{ env.ISSUE_REPOSITORY }}
          issue-number: ${{ env.ISSUE_NUMBER }}
          file: ${{ env.STEP_2_FILE }}

      - name: コメントを作成 - 進捗待ち
        uses: GrantBirki/comment@v2.1.1
        with:
          repository: ${{ env.ISSUE_REPOSITORY }}
          issue-number: ${{ env.ISSUE_NUMBER }}
          file: .github/ja-templates/step-feedback/watching-for-progress.md

      - name: 現在の workflow を無効化し、次を有効化
        run: |
          gh workflow disable "${{github.workflow}}"
          gh workflow enable "2-step.yml"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
